version: '3'
services:
 yii-db:
  image: mariadb:latest
  ports:
   - "3306:3306"
  volumes:
   - /data/yii/dbdata:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=astrongpassword
  hostname: yii-db
    
 yii-web:
  image: thomaszastrow/yii-dev:latest
  ports:
   - "9090:80"
  volumes:
   - /data/yii/webdata:/var/www/html
  hostname: yii-web

